# Facial Visual Profile — RQ5
## Nonlinear fusion and auxiliary landmark supervision

In [1]:
# 1 — GPU, Drive and pinned source. No package upgrades.
import os, sys, json, hashlib, shutil, subprocess, platform, time, gc
from pathlib import Path
import importlib.metadata
import torch

assert torch.cuda.is_available(), (
    'CUDA 不可用'
    ' GPU 运行时仍显示 +cpu'
)
import torchvision
import numpy as np
import pandas as pd
from PIL import Image, __version__ as pillow_version
from google.colab import drive

drive.mount('/content/drive')
COMMIT = '1788617b6271dbb1d9b075660c0398cd2782eaf5'
REPO = Path('/content/fvp_rq5_notebook_repo')
PROJECT = Path('/content/drive/MyDrive/FacialVisualProfile')
STUDY = PROJECT/'runs/rq5_training_v1'
LOCAL = Path('/content/fvp_rq5_data')
IMAGES = LOCAL/'img_align_celeba'
ROOTS = [PROJECT/'runs/benchmark/day19/shards', PROJECT/'runs/benchmark/day20/shards']
assert PROJECT.is_dir()
if not REPO.exists():
    subprocess.run(['git','clone','https://github.com/DeweyYip/facial-visual-profile.git',str(REPO)],check=True)
def git(*args):
    return subprocess.check_output(['git','-C',str(REPO),*args],text=True).strip()
assert not git('status','--porcelain'), 'Pinned checkout changed; preserve changes and use a fresh runtime.'
if git('rev-parse','HEAD') != COMMIT:
    subprocess.run(['git','-C',str(REPO),'fetch','origin'],check=True)
    subprocess.run(['git','-C',str(REPO),'checkout','--detach',COMMIT],check=True)
assert git('rev-parse','HEAD') == COMMIT
STUDY.mkdir(parents=True,exist_ok=True)
LOCAL.mkdir(parents=True,exist_ok=True)
ENVIRONMENT = dict(python=platform.python_version(),torch=str(torch.__version__),
    torchvision=str(torchvision.__version__),numpy=np.__version__,Pillow=pillow_version,
    sklearn=importlib.metadata.version('scikit-learn'),cuda=torch.version.cuda,
    gpu=torch.cuda.get_device_name(0))
print(json.dumps(ENVIRONMENT,indent=2),flush=True)
print('SOURCE:',COMMIT,flush=True)
print('This run will train nine models after all preparation checks pass.',flush=True)

Mounted at /content/drive
{
  "python": "3.13.16",
  "torch": "2.11.0+cu130",
  "torchvision": "0.26.0+cu130",
  "numpy": "2.1.3",
  "Pillow": "11.3.0",
  "sklearn": "1.6.1",
  "cuda": "13.0",
  "gpu": "Tesla T4"
}
SOURCE: 1788617b6271dbb1d9b075660c0398cd2782eaf5
This run will train nine models after all preparation checks pass.

In [2]:
# 2 — Recorded runtime fixes, source snapshot and restart bindings.
import copy

def digest(path):
    h=hashlib.sha256()
    with open(path,'rb') as source:
        for block in iter(lambda:source.read(8*1024*1024),b''):
            h.update(block)
    return h.hexdigest()

def write_json(path,value):
    path=Path(path); path.parent.mkdir(parents=True,exist_ok=True)
    temp=path.with_name(path.name+'.partial')
    temp.write_text(json.dumps(value,indent=2,allow_nan=False)+'\n')
    temp.replace(path)

def seal(path,value):
    if path.exists():
        assert json.loads(path.read_text())==value, f'Frozen record differs: {path}. Stop; do not delete old runs.'
    else:
        write_json(path,value)

# A separate local source copy keeps the pinned Git checkout pristine.
WORK=Path('/content/fvp_rq5_execution')
if WORK.exists():
    shutil.rmtree(WORK)
shutil.copytree(REPO,WORK,ignore=shutil.ignore_patterns('.git','__pycache__'))
path=WORK/'training/rq5.py'
s=path.read_text()
def replace_once(old,new):
    global s
    assert s.count(old)==1, 'Pinned training source differs from reviewed code'
    s=s.replace(old,new,1)

# Completed runs must not rewrite best_model.pt, whose byte hash binds thresholds.
replace_once('    bind_run(folder,config,name,seed)\n', '''    bind_run(folder,config,name,seed)
    if (folder/'train_complete.json').exists():
        done = json.loads((folder/'train_complete.json').read_text())
        assert (folder/'latest.pt').exists() and (folder/'best_model.pt').exists()
        selected = torch.load(folder/'best_model.pt',map_location='cpu',weights_only=True)
        assert selected['exp']==name and selected['seed']==seed
        assert selected['epoch']==done['best']['epoch']
        print('SKIP completed training:',folder.name,'epochs:',done['epochs'],flush=True)
        return
    # A first-epoch disconnect can leave sidecars before latest.pt commits.
    # Preserve these uncommitted files, then repeat epoch 1 from its original seed.
    if not (folder/'latest.pt').exists():
        orphans = [folder/f for f in ('history.json','best.json','best_model.pt') if (folder/f).exists()]
        if orphans:
            import time
            recovery = folder/'uncommitted_recovery'/str(time.time_ns())
            recovery.mkdir(parents=True)
            for orphan in orphans:
                orphan.replace(recovery/orphan.name)
            print('Preserved uncommitted first-epoch sidecars:',recovery,flush=True)
''')
# Never change best checkpoint bytes when resuming a matching selected epoch.
replace_once("        write_torch(folder/'best_model.pt',dict(model=best_state,exp=name,seed=seed,epoch=best['epoch']))", '''        best_path = folder/'best_model.pt'
        existing = torch.load(best_path,map_location='cpu',weights_only=True) if best_path.exists() else None
        if existing is None or existing['epoch'] != best['epoch']:
            assert not (folder/'clean_val_thresholds.json').exists(), 'Do not replace a threshold-bound checkpoint'
            write_torch(best_path,dict(model=best_state,exp=name,seed=seed,epoch=best['epoch']))''')
replace_once("        history,best = saved['history'],saved['best']", "        history,best = saved['history'],saved['best']\n        print('RESUME:',folder.name,'last complete epoch:',saved['epoch'],flush=True)")
replace_once('        for batch in make_loader(train,config,True,seed+epoch):', '''        print('TRAIN:',folder.name,'epoch',epoch,'/',config['epochs'],flush=True)
        for batch_index,batch in enumerate(make_loader(train,config,True,seed+epoch)):
            if batch_index % 250 == 0:
                print('  train batches:',batch_index,'samples:',seen,'/',len(train),flush=True)''')
replace_once('    for batch in make_loader(dataset, config):', '''    for batch_index,batch in enumerate(make_loader(dataset, config)):
        if batch_index % 80 == 0:
            print('  inference batches:',batch_index,'/',len(dataset)//config['eval_batch_size']+1,flush=True)''')
# Binding must include NumPy/sklearn and device metadata as well as old fields.
replace_once("torchvision=torchvision.__version__,Pillow=pillow_version,cuda=torch.version.cuda)", "torchvision=torchvision.__version__,Pillow=pillow_version,cuda=torch.version.cuda,\n        numpy=np.__version__,sklearn=__import__('sklearn').__version__,gpu=torch.cuda.get_device_name(0))")
compile(s,str(path),'exec')
path.write_text(s)

os.chdir(WORK)
sys.path.insert(0,str(WORK))
# Drive keeps pretrained files too; no detector installation/inference is needed.
os.environ['TORCH_HOME']=str(PROJECT/'cache/rq5_torch_home')
os.environ['PYTHONUNBUFFERED']='1'
# Retain PyTorch defaults for TF32, matching the RQ4 code's lack of overrides.
from training import rq5 as train
from datasets.celeba_rq5 import CelebARQ5, ATTRIBUTES
from training.rq5_shared import set_seed

from models.rq5 import make_model
import datasets.celeba_rq5 as dataset_module
assert Path(train.__file__).resolve().is_relative_to(WORK), 'Restart runtime: stale training module import'
assert Path(dataset_module.__file__).resolve().is_relative_to(WORK), 'Restart runtime: local datasets package shadowed'
from scripts.evaluate_rq5 import conditions, report
from datasets.corruptions import apply_corruption, rgb_sha256
from training.rq5_shared import prepare_canvas, transform_corruption

# Pin auxiliary baseline source and the notebook patch, not just the Git commit.
SOURCE_FILES=['models/rq5.py','datasets/celeba_rq5.py','training/rq5.py',
    'training/rq5_shared.py','scripts/evaluate_rq5.py','datasets/landmark_cache.py',
    'datasets/corruptions.py','configs/rq5_training_v1.json']
SOURCE={p:digest(WORK/p) for p in SOURCE_FILES}
BINDING=dict(commit=COMMIT,notebook_revision='rq5_colab_v1',sources=SOURCE,
             environment=ENVIRONMENT,tf32_matmul=torch.backends.cuda.matmul.allow_tf32,
             tf32_cudnn=torch.backends.cudnn.allow_tf32)
seal(STUDY/'notebook_execution_binding.json',BINDING)
for relative in SOURCE_FILES:
    destination=STUDY/'source_snapshot'/relative
    destination.parent.mkdir(parents=True,exist_ok=True)
    if destination.exists():
        assert digest(destination)==SOURCE[relative]
    else:
        shutil.copyfile(WORK/relative,destination)
parameter_counts={}
for name in ('N0','N1','MTL'):
    temporary=make_model(name,pretrained=False)
    parameter_counts[name]=sum(p.numel() for p in temporary.parameters() if p.requires_grad)
    del temporary
assert parameter_counts=={'N0':11249368,'N1':11250776,'MTL':11193954}
seal(STUDY/'model_parameter_counts.json',parameter_counts)
print('Parameters:',parameter_counts,flush=True)
print('SOURCE / ENVIRONMENT BINDING PASS',flush=True)

Parameters: {'N0': 11249368, 'N1': 11250776, 'MTL': 11193954}
SOURCE / ENVIRONMENT BINDING PASS

In [3]:
# 3 — Original data integrity, annotation checks and resumable local extraction.
import zipfile
RAW=PROJECT/'data'
REQUIRED=['img_align_celeba.zip','list_eval_partition.txt','list_attr_celeba.txt','list_landmarks_align_celeba.txt']
for name in REQUIRED:
    assert (RAW/name).is_file(), f'Missing: {RAW/name}'
assert (PROJECT/'cache/mtcnn_clean.sqlite').is_file()
for root in ROOTS:
    assert root.is_dir(),f'Missing benchmark shards: {root}'

print('Hashing original CelebA ZIP and annotations...',flush=True)
EXPECTED_ZIP='46fb89443c578308acf364d7d379fe1b9efb793042c0af734b6112e4fd3a8c74'
assert digest(RAW/'img_align_celeba.zip')==EXPECTED_ZIP,'Original ZIP differs'
ASSETS={name:digest(RAW/name) for name in REQUIRED}
ASSETS['mtcnn_clean.sqlite']=digest(PROJECT/'cache/mtcnn_clean.sqlite')
seal(STUDY/'input_asset_binding.json',ASSETS)

pairs=[row.split() for row in (RAW/'list_eval_partition.txt').read_text(encoding='utf-8-sig').splitlines()]
partitions=dict(pairs)
assert len(pairs)==len(partitions)==202599
from collections import Counter
assert Counter(partitions.values())=={'0':162770,'1':19867,'2':19962}
# Same official ordering as RQ4, not a newly shuffled/sampled split.
for split in ('0','1','2'):
    selected=[name for name,code in pairs if code==split]
    assert selected==sorted(selected),'RQ4 partition file is not filename-sorted; do not silently change order'

archive=LOCAL/'img_align_celeba.zip'
if not archive.exists() or digest(archive)!=EXPECTED_ZIP:
    print('Copying ZIP from Drive to local disk...',flush=True)
    temp=archive.with_name(archive.name+'.partial')
    shutil.copyfile(RAW/'img_align_celeba.zip',temp)
    assert digest(temp)==EXPECTED_ZIP
    temp.replace(archive)
IMAGES.mkdir(parents=True,exist_ok=True)
with zipfile.ZipFile(archive) as z:
    members={}
    for info in z.infolist():
        if info.is_dir():
            continue
        name=Path(info.filename).name
        assert name not in members and name in partitions
        members[name]=info
    assert set(members)==set(partitions)
    for i,name in enumerate(sorted(members),1):
        info=members[name]; dst=IMAGES/name
        if not dst.is_file() or dst.stat().st_size!=info.file_size:
            temp=dst.with_name(dst.name+'.partial')
            with z.open(info) as source, temp.open('wb') as output:
                shutil.copyfileobj(source,output)
            temp.replace(dst)
        if i%40000==0:
            print('Local images ready:',i,'/',len(members),flush=True)
assert all((IMAGES/name).is_file() for name in partitions)
print('DATA PREPARATION PASS:',len(partitions),'images',flush=True)

Hashing original CelebA ZIP and annotations...
Copying ZIP from Drive to local disk...
Local images ready: 40000 / 202599
Local images ready: 80000 / 202599
Local images ready: 120000 / 202599
Local images ready: 160000 / 202599
Local images ready: 200000 / 202599
DATA PREPARATION PASS: 202599 images

In [4]:
# 4 — Audit all three original RQ4-A runs before adding MTL.
BASELINE=PROJECT/'runs/rq4_training_v1'
old_protocol=json.loads((BASELINE/'study_protocol.json').read_text())
expected=dict(epochs=10,batch_size=64,lr=1e-4,weight_decay=0.,num_workers=2,
    image_size=224,pretrained='ResNet18_Weights.IMAGENET1K_V1',
    checkpoint_selection='maximum clean-validation mAP; earliest epoch on exact tie')
for key,value in expected.items():
    assert old_protocol[key]==value, f'RQ4 protocol differs: {key}'
assert old_protocol['attributes']==ATTRIBUTES
assert old_protocol['seeds']==[0,1,2]
assert old_protocol['experiments']['A']==dict(geometry=False,augmentation=False,mask_rgb=False)
policy=json.loads((BASELINE/'early_stopping_policy.json').read_text())
assert policy['enabled'] is True
assert (policy['max_epochs'],policy['min_epochs'],policy['patience'])==(10,4,2)
old_runs={}
for seed in (0,1,2):
    folder=BASELINE/f'A_seed{seed}'
    for filename in ['config.json','history.json','best.json','best_model.pt',
                     'train_complete.json','clean_val_thresholds.json','test_metrics.json','test_complete.json']:
        assert (folder/filename).is_file(),f'Missing old baseline: {folder/filename}'
    cfg=json.loads((folder/'config.json').read_text())
    assert cfg['exp']=='A' and cfg['seed']==seed
    assert cfg['protocol']==old_protocol and cfg['options']==old_protocol['experiments']['A']
    thresholds=json.loads((folder/'clean_val_thresholds.json').read_text())
    assert thresholds['attribute_order']==ATTRIBUTES and len(thresholds['thresholds'])==24
    results=json.loads((folder/'test_metrics.json').read_text())
    assert set(results)=={label for label,_,_ in conditions()}
    history=json.loads((folder/'history.json').read_text())
    best=json.loads((folder/'best.json').read_text())
    selected=max(history,key=lambda row:row['clean_validation_mAP'])
    assert selected['epoch']==best['epoch']
    done=json.loads((folder/'train_complete.json').read_text())
    assert done['epochs']==history[-1]['epoch']
    old_runs[str(seed)]={name:digest(folder/name) for name in
        ['config.json','history.json','best.json','best_model.pt','clean_val_thresholds.json','test_metrics.json']}
    print('RQ4 A seed',seed,'audit PASS; selected epoch',best['epoch'],flush=True)
seal(STUDY/'rq4_baseline_binding.json',old_runs)
if (BASELINE/'runtime_latest.json').exists():
    runtime=json.loads((BASELINE/'runtime_latest.json').read_text())
    print('Historical RQ4 latest runtime record (not per-seed proof):',runtime,flush=True)
    print('Current runtime:',ENVIRONMENT,flush=True)
    write_json(STUDY/'historical_environment_comparison.json',dict(
        old_latest_record=runtime,current=ENVIRONMENT,
        interpretation='Environment differences limit strict paired causal interpretation; no A retraining.'))
print('RQ4-A protocol/records audit PASS. Historical metric bytes remain untouched.',flush=True)

RQ4 A seed 0 audit PASS; selected epoch 2
RQ4 A seed 1 audit PASS; selected epoch 2
RQ4 A seed 2 audit PASS; selected epoch 2
Historical RQ4 latest runtime record (not per-seed proof): {'python': '3.13.15', 'torch': '2.11.0+cu130', 'torchvision': '0.26.0+cu130', 'Pillow': '11.3.0', 'device': 'cuda', 'cuda': '13.0'}
Current runtime: {'python': '3.13.16', 'torch': '2.11.0+cu130', 'torchvision': '0.26.0+cu130', 'numpy': '2.1.3', 'Pillow': '11.3.0', 'sklearn': '1.6.1', 'cuda': '13.0', 'gpu': 'Tesla T4'}
RQ4-A protocol/records audit PASS. Historical metric bytes remain untouched.

In [5]:
# 5 — Reuse archived preflight and frozen lambda.
saved_binding = json.loads(
    (STUDY / "notebook_execution_binding.json").read_text()
)
assert saved_binding == BINDING, "源码或环境与原运行不同，停止。"

saved_assets = json.loads(
    (STUDY / "input_asset_binding.json").read_text()
)
assert saved_assets == ASSETS, "输入资产与原运行不同，停止。"

preflight = json.loads(
    (STUDY / "frozen_input_preflight.json").read_text()
)
expected = {label for label, _, _ in conditions()}
assert len(preflight) == 21
assert {row["condition"] for row in preflight} == expected

scale = json.loads(
    (STUDY / "lambda_scale_check.json").read_text()
)
frozen = json.loads(
    (STUDY / "frozen_config.json").read_text()
)
assert scale["source"] == SOURCE
assert frozen["mtl_lambda"] == scale["lambda"]

print("SKIP: 已完成的 21 条件检查。")
print("已冻结 λ =", frozen["mtl_lambda"])

Inspecting original-image caches...
train cache statuses: {'ok': 162521, 'no_face': 249}
  train ok 000001.jpg PASS
  train no_face 000199.jpg PASS
valid cache statuses: {'ok': 19835, 'no_face': 32}
  valid ok 162771.jpg PASS
  valid no_face 162871.jpg PASS
Frozen input/cache parity: clean PASS
Frozen input/cache parity: blur_s1 PASS
Frozen input/cache parity: blur_s2 PASS
Frozen input/cache parity: blur_s3 PASS
Frozen input/cache parity: blur_s4 PASS
Frozen input/cache parity: brightness_s1 PASS
Frozen input/cache parity: brightness_s2 PASS
Frozen input/cache parity: brightness_s3 PASS
Frozen input/cache parity: brightness_s4 PASS
Frozen input/cache parity: rotation_s1 PASS
Frozen input/cache parity: rotation_s2 PASS
Frozen input/cache parity: rotation_s3 PASS
Frozen input/cache parity: rotation_s4 PASS
Frozen input/cache parity: occlusion_s1 PASS
Frozen input/cache parity: occlusion_s2 PASS
Frozen input/cache parity: occlusion_s3 PASS
Frozen input/cache parity: occlusion_s4 PASS
Frozen input/cache parity: jpeg_s1 PASS
Frozen input/cache parity: jpeg_s2 PASS
Frozen input/cache parity: jpeg_s3 PASS
Frozen input/cache parity: jpeg_s4 PASS
N1 CUDA interface and failure masking PASS
MTL CUDA shared-backbone gradients PASS
REAL DATA / CUDA / FAILURE MASK PREFLIGHT PASS

## settle λ, and then train

In [6]:
# 6 — Freeze one training-only loss-scale lambda. No trial training.
CONFIG_PATH=STUDY/'frozen_config.json'
SCALE_PATH=STUDY/'lambda_scale_check.json'
base_config=train.load_config(WORK/'configs/rq5_training_v1.json')
if SCALE_PATH.exists():
    scale=json.loads(SCALE_PATH.read_text())
    assert scale['rule']=='mean_BCE_over_mean_MSE_4_train_batches_6_significant_digits_v1'
    print('REUSE frozen lambda:',scale['lambda'],flush=True)
else:
    # Never derive a new lambda once any official run has started.
    assert not any((STUDY/f'{name}_seed{seed}'/'config.json').exists()
                   for name in base_config['models'] for seed in base_config['seeds'])
    set_seed(0)
    model=make_model('MTL',pretrained=True).cuda().train()
    ds=CelebARQ5(PROJECT,IMAGES,'train','MTL')
    values=[]
    with torch.no_grad():
        for i,batch in enumerate(train.make_loader(ds,base_config,True,seed=1)):
            logits,coordinates=model(batch['image'].cuda())
            bce=torch.nn.functional.binary_cross_entropy_with_logits(logits,batch['target'].cuda())
            mse=torch.nn.functional.mse_loss(coordinates,batch['gt'].cuda())
            assert torch.isfinite(bce) and torch.isfinite(mse) and mse>0
            values.append(dict(batch=i,BCE=bce.item(),MSE=mse.item(),names=batch['name']))
            if i==3:
                break
    weight=float(f"{np.mean([v['BCE'] for v in values])/np.mean([v['MSE'] for v in values]):.6g}")
    assert np.isfinite(weight) and weight>0
    scale=dict(rule='mean_BCE_over_mean_MSE_4_train_batches_6_significant_digits_v1',
        seed=0,loader_seed=1,lambda_value=weight,batches=values,source=SOURCE)
    scale['lambda']=weight
    write_json(SCALE_PATH,scale)
    del model,ds,batch
    gc.collect();torch.cuda.empty_cache()
CONFIG=dict(base_config)
CONFIG['mtl_lambda']=scale['lambda']
CONFIG['lambda_basis']=scale['rule']+'; see lambda_scale_check.json'
seal(CONFIG_PATH,CONFIG)
assert train.load_config(CONFIG_PATH)==CONFIG
print('FROZEN lambda:',CONFIG['mtl_lambda'],flush=True)
print('Config:',CONFIG_PATH,flush=True)

REUSE frozen lambda: 1.89811
FROZEN lambda: 1.89811
Config: /content/drive/MyDrive/FacialVisualProfile/runs/rq5_training_v1/frozen_config.json

In [7]:
# 7 — Run all nine trainings and threshold exports with logs and epoch resume.
# Logs append across sessions; a subprocess failure stops this notebook.
def logged(command,log_path):
    log_path.parent.mkdir(parents=True,exist_ok=True)
    with log_path.open('a',buffering=1) as log:
        log.write('\nSESSION '+time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime())+'\n')
        process=subprocess.Popen(command,cwd=str(WORK),stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,text=True,bufsize=1,env=os.environ.copy())
        try:
            for line in process.stdout:
                print(line,end='',flush=True)
                log.write(line)
            status=process.wait()
        except BaseException:
            process.terminate()
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                process.kill();process.wait()
            raise
        assert status==0,f'Execution stopped ({status}); inspect {log_path}. Resume by rerunning notebook.'

for name in CONFIG['models']:
    for seed in CONFIG['seeds']:
        print('\n=== TRAIN / RESUME:',name,'seed',seed,'===',flush=True)
        logged([sys.executable,'-u','-m','training.rq5',
            '--project',str(PROJECT),'--images',str(IMAGES),'--config',str(CONFIG_PATH),
            '--model',name,'--seed',str(seed)],STUDY/'logs'/f'{name}_seed{seed}_training.log')

for name in CONFIG['models']:
    for seed in CONFIG['seeds']:
        folder=STUDY/f'{name}_seed{seed}'
        assert (folder/'train_complete.json').is_file()
        assert (folder/'clean_val_thresholds.json').is_file()
print('ALL NINE TRAININGS AND FROZEN THRESHOLDS COMPLETE',flush=True)

=== TRAIN / RESUME: N0 seed 0 ===
RESUME: N0_seed0 last complete epoch: 2
TRAIN: N0_seed0 epoch 3 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 {'epoch': 3, 'training_loss': 0.17607025218356365, 'attribute_BCE': 0.17607025218356365, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8165720348143997, 'clean_validation_F1_at_05': 0.7275355406994155}
TRAIN: N0_seed0 epoch 4 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 {'epoch': 4, 'training_loss': 0.1627267521175243, 'attribute_BCE': 0.1627267521175243, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8126598990955266, 'clean_validation_F1_at_05': 0.7349692159731113}
  inference batches: 0 / 156
  inference batches: 80 / 156

=== TRAIN / RESUME: N0 seed 1 ===
TRAIN: N0_seed1 epoch 1 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 {'epoch': 1, 'training_loss': 0.21959729673049225, 'attribute_BCE': 0.21959729673049225, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8095045821354988, 'clean_validation_F1_at_05': 0.7260989153223819}
TRAIN: N0_seed1 epoch 2 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 {'epoch': 2, 'training_loss': 0.1878235448254131, 'attribute_BCE': 0.1878235448254131, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8176928477631383, 'clean_validation_F1_at_05': 0.7286936751815954}
TRAIN: N0_seed1 epoch 3 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 {'epoch': 3, 'training_loss': 0.176327753580231, 'attribute_BCE': 0.176327753580231, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8160483810683911, 'clean_validation_F1_at_05': 0.7349817448108785}
TRAIN: N0_seed1 epoch 4 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 {'epoch': 4, 'training_loss': 0.16298554163182874, 'attribute_BCE': 0.16298554163182874, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8085825556105454, 'clean_validation_F1_at_05': 0.730014003299531}
  inference batches: 0 / 156
  inference batches: 80 / 156

=== TRAIN / RESUME: N0 seed 2 ===
TRAIN: N0_seed2 epoch 1 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 {'epoch': 1, 'training_loss': 0.2187361981433418, 'attribute_BCE': 0.2187361981433418, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8111972262912372, 'clean_validation_F1_at_05': 0.7185100570974475}
TRAIN: N0_seed2 epoch 2 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 {'epoch': 2, 'training_loss': 0.18799334183283123, 'attribute_BCE': 0.18799334183283123, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.817060553880113, 'clean_validation_F1_at_05': 0.7375194965964473}
TRAIN: N0_seed2 epoch 3 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 {'epoch': 3, 'training_loss': 0.1765776514871529, 'attribute_BCE': 0.1765776514871529, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8127579092476257, 'clean_validation_F1_at_05': 0.7326757843815793}
TRAIN: N0_seed2 epoch 4 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 {'epoch': 4, 'training_loss': 0.1631303681457644, 'attribute_BCE': 0.1631303681457644, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8151436551539827, 'clean_validation_F1_at_05': 0.7485287902924279}
  inference batches: 0 / 156
  inference batches: 80 / 156

=== TRAIN / RESUME: N1 seed 0 ===
TRAIN: N1_seed0 epoch 1 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 {'epoch': 1, 'training_loss': 0.2192393515061972, 'attribute_BCE': 0.2192393515061972, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8115000651851183, 'clean_validation_F1_at_05': 0.7297779079361787}
TRAIN: N1_seed0 epoch 2 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 {'epoch': 2, 'training_loss': 0.1880438698660414, 'attribute_BCE': 0.1880438698660414, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8174672875595901, 'clean_validation_F1_at_05': 0.7368021325791426}
TRAIN: N1_seed0 epoch 3 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 {'epoch': 3, 'training_loss': 0.17634887250117764, 'attribute_BCE': 0.17634887250117764, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8167310814103894, 'clean_validation_F1_at_05': 0.7284455733355725}
TRAIN: N1_seed0 epoch 4 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 {'epoch': 4, 'training_loss': 0.1632804444346387, 'attribute_BCE': 0.1632804444346387, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8128782978100101, 'clean_validation_F1_at_05': 0.7380396056912485}
  inference batches: 0 / 156
  inference batches: 80 / 156

=== TRAIN / RESUME: N1 seed 1 ===
TRAIN: N1_seed1 epoch 1 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 {'epoch': 1, 'training_loss': 0.21889338108958178, 'attribute_BCE': 0.21889338108958178, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.810488303033473, 'clean_validation_F1_at_05': 0.7219583529118271}
TRAIN: N1_seed1 epoch 2 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 {'epoch': 2, 'training_loss': 0.18804793070555245, 'attribute_BCE': 0.18804793070555245, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8164394439177108, 'clean_validation_F1_at_05': 0.7257749037537068}
TRAIN: N1_seed1 epoch 3 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 {'epoch': 3, 'training_loss': 0.1765040970241554, 'attribute_BCE': 0.1765040970241554, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8162664930306326, 'clean_validation_F1_at_05': 0.7339882336795839}
TRAIN: N1_seed1 epoch 4 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 {'epoch': 4, 'training_loss': 0.16331911646335476, 'attribute_BCE': 0.16331911646335476, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8082073306244749, 'clean_validation_F1_at_05': 0.7274770291028009}
  inference batches: 0 / 156
  inference batches: 80 / 156

=== TRAIN / RESUME: N1 seed 2 ===
TRAIN: N1_seed2 epoch 1 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 {'epoch': 1, 'training_loss': 0.21862534554876054, 'attribute_BCE': 0.21862534554876054, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8098594530490644, 'clean_validation_F1_at_05': 0.7167054039579103}
TRAIN: N1_seed2 epoch 2 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 {'epoch': 2, 'training_loss': 0.18791475692493745, 'attribute_BCE': 0.18791475692493745, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8171374714559442, 'clean_validation_F1_at_05': 0.7367071848077771}
TRAIN: N1_seed2 epoch 3 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 {'epoch': 3, 'training_loss': 0.17645804361786005, 'attribute_BCE': 0.17645804361786005, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8128819236657377, 'clean_validation_F1_at_05': 0.7249762088396287}
TRAIN: N1_seed2 epoch 4 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 {'epoch': 4, 'training_loss': 0.16301633528946233, 'attribute_BCE': 0.16301633528946233, 'landmark_MSE': 0.0, 'clean_validation_mAP': 0.8143309871851688, 'clean_validation_F1_at_05': 0.7462909103251706}
  inference batches: 0 / 156
  inference batches: 80 / 156

=== TRAIN / RESUME: MTL seed 0 ===
TRAIN: MTL_seed0 epoch 1 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 {'epoch': 1, 'training_loss': 0.23038492586946374, 'attribute_BCE': 0.22487110838851554, 'landmark_MSE': 0.002904898721508525, 'clean_validation_mAP': 0.8098114636852746, 'clean_validation_F1_at_05': 0.7258242382296402}
TRAIN: MTL_seed0 epoch 2 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770
  train batches: 1000 samples: 64000 / 162770
  train batches: 1250 samples: 80000 / 162770
  train batches: 1500 samples: 96000 / 162770
  train batches: 1750 samples: 112000 / 162770
  train batches: 2000 samples: 128000 / 162770
  train batches: 2250 samples: 144000 / 162770
  train batches: 2500 samples: 160000 / 162770
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 {'epoch': 2, 'training_loss': 0.19149551111997665, 'attribute_BCE': 0.18978807351791632, 'landmark_MSE': 0.0008995461761841876, 'clean_validation_mAP': 0.8161002470951515, 'clean_validation_F1_at_05': 0.7327443632510082}
TRAIN: MTL_seed0 epoch 3 / 10
  train batches: 0 samples: 0 / 162770
  train batches: 250 samples: 16000 / 162770
  train batches: 500 samples: 32000 / 162770
  train batches: 750 samples: 48000 / 162770

In [8]:
# 8 — Final 21-condition evaluation. Resume at condition boundaries.
# N1 first: all samples are checked against archived final RGB hashes.
for name in ('N1','N0','MTL'):
    for seed in CONFIG['seeds']:
        print('\n=== FINAL TEST / RESUME:',name,'seed',seed,'===',flush=True)
        command=[sys.executable,'-u','scripts/evaluate_rq5.py',
            '--project',str(PROJECT),'--images',str(IMAGES),'--config',str(CONFIG_PATH),
            '--model',name,'--seed',str(seed)]
        if name=='N1':
            command+=['--benchmark-roots',*[str(root) for root in ROOTS]]
        logged(command,STUDY/'logs'/f'{name}_seed{seed}_test.log')
print('ALL NINE 21-CONDITION EVALUATIONS COMPLETE',flush=True)

=== FINAL TEST / RESUME: N1 seed 0 ===
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 clean 0.8202498088010248 0.7581471534728657
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 blur_s1 0.8055081573314311 0.7107474305246607
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 blur_s2 0.7510074526419223 0.5298718805910845
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 blur_s3 0.6683483637967353 0.2849539513279555
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 blur_s4 0.5619453066566931 0.13637323737902546
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 brightness_s1 0.8192157312684186 0.7542625047029151
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 brightness_s2 0.8143373689425285 0.7429876552856163
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 brightness_s3 0.8013652209320044 0.7099655675963525
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 brightness_s4 0.7581104068007006 0.5583154280997743
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 rotation_s1 0.8126229529389896 0.7401849823951864
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 rotation_s2 0.8016502862587972 0.7143064696426835
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 rotation_s3 0.7894380473642523 0.6852673039355862
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 rotation_s4 0.7725626830035551 0.6422378185091535
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 occlusion_s1 0.8037403129244837 0.7163074948308932
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 occlusion_s2 0.758684734046307 0.5675780220853796
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 occlusion_s3 0.7015409439824212 0.4872917626809284
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 occlusion_s4 0.6467629322534262 0.3785341647460967
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 jpeg_s1 0.8173674666677812 0.7542490650126069
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 jpeg_s2 0.813465733711598 0.7500419086558977
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 jpeg_s3 0.8007167638790665 0.7310935349736521
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 0 jpeg_s4 0.7386115205725354 0.6020991079602941

=== FINAL TEST / RESUME: N1 seed 1 ===
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 clean 0.8192908558213086 0.7528618574452458
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 blur_s1 0.8045265982805206 0.713327970781452
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 blur_s2 0.7509696539399012 0.5269408489560928
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 blur_s3 0.6686944055188059 0.2861807250571376
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 blur_s4 0.5630942073680866 0.12003309364429438
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 brightness_s1 0.8176471255512832 0.7511175477494136
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 brightness_s2 0.8121736611715438 0.7436309408508918
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 brightness_s3 0.7990668461532003 0.7221598236819536
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 brightness_s4 0.7567161064501008 0.5867147405712875
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 rotation_s1 0.8124111259418859 0.738818316623011
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 rotation_s2 0.8027255946430664 0.7197299343266889
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 rotation_s3 0.7920331370405594 0.693410916972522
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 rotation_s4 0.776300628872432 0.6556904698243886
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 occlusion_s1 0.8022369354603276 0.7030556029324044
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 occlusion_s2 0.7520075035949264 0.548008081816398
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 occlusion_s3 0.6972590570728547 0.49024295572818893
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 occlusion_s4 0.6455715315691698 0.4057436444056653
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 jpeg_s1 0.8165113540857115 0.7502421068065906
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 jpeg_s2 0.812769805562464 0.7447087425416775
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 jpeg_s3 0.8012178610081376 0.7245706497092724
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 1 jpeg_s4 0.7459911679684111 0.6036097970894668

=== FINAL TEST / RESUME: N1 seed 2 ===
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 clean 0.816591790337855 0.7535711355034737
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 blur_s1 0.8015577010805854 0.7116024081935844
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 blur_s2 0.74357379807059 0.5175306756414608
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 blur_s3 0.6631005416834871 0.27406277407911506
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 blur_s4 0.5682876854432181 0.11722939390210822
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 brightness_s1 0.8159851942018245 0.7505686525662126
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 brightness_s2 0.8121585316961554 0.7433925907137774
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 brightness_s3 0.7997772611877441 0.7176260521672493
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 brightness_s4 0.7548335985765086 0.5798902480944196
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 rotation_s1 0.8093766983714961 0.7404172323599192
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 rotation_s2 0.799425464417357 0.7219570497869062
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 rotation_s3 0.7888423020655436 0.7013553898637358
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 rotation_s4 0.7731255737413504 0.6720968548074487
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 occlusion_s1 0.798686108566624 0.7097979197552956
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 occlusion_s2 0.7471669252823782 0.5587306159979839
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 occlusion_s3 0.6834537231404775 0.4901279640011949
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 occlusion_s4 0.6275228867478196 0.38749595785146074
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 jpeg_s1 0.8142014487106951 0.751532793630106
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 jpeg_s2 0.8104799014745949 0.7461009305846394
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 jpeg_s3 0.7977310638848983 0.7257733677697008
  inference batches: 0 / 156
  inference batches: 80 / 156
N1 2 jpeg_s4 0.7369614941364356 0.6118425350286029

=== FINAL TEST / RESUME: N0 seed 0 ===
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 clean 0.8198199614872826 0.7566263899530575
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 blur_s1 0.8046745027449719 0.7078430306105584
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 blur_s2 0.7503797724554634 0.5303557388050912
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 blur_s3 0.6715354565651639 0.29221061740473936
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 blur_s4 0.5556990840989805 0.1201094042898257
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 brightness_s1 0.818713234284686 0.7556322413504106
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 brightness_s2 0.8144576457743075 0.7466402297011875
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 brightness_s3 0.803547189444418 0.7215136294396925
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 brightness_s4 0.7664366346641005 0.5887820477161815
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 rotation_s1 0.8119695038087134 0.7406065355078536
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 rotation_s2 0.802129516536963 0.7249519426220505
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 rotation_s3 0.7907071861338899 0.7033294055939984
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 rotation_s4 0.7753550391485579 0.6698423034546485
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 occlusion_s1 0.8040566574701135 0.7041135090634852
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 occlusion_s2 0.7547485908409824 0.5455533181644989
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 occlusion_s3 0.6955317558137307 0.4826770551974531
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 occlusion_s4 0.6425485411188289 0.40068550564380506
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 jpeg_s1 0.8169578175728626 0.7528421376855666
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 jpeg_s2 0.8136514286559485 0.7487932855308485
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 jpeg_s3 0.8013901152259374 0.7292987881271826
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 0 jpeg_s4 0.7364883287810912 0.5979540136102942

=== FINAL TEST / RESUME: N0 seed 1 ===
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 clean 0.8196598481182956 0.7553906367272489
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 blur_s1 0.80443565012472 0.7125836881659007
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 blur_s2 0.7493234539322199 0.5393218056661543
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 blur_s3 0.6598967986779942 0.2691048641036111
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 blur_s4 0.5428629418076018 0.1024165356782028
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 brightness_s1 0.8181912010706989 0.7529560512102281
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 brightness_s2 0.8129978670015273 0.7453049368516469
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 brightness_s3 0.8005475664200553 0.722455889078505
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 brightness_s4 0.7587469396342638 0.6130018426010374
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 rotation_s1 0.8121830788035768 0.7408241112198013
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 rotation_s2 0.8025071558090802 0.7167889599128733
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 rotation_s3 0.7910415811839965 0.6864109257585805
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 rotation_s4 0.7738618937314348 0.6496976771817154
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 occlusion_s1 0.8025801258476327 0.7026695158690192
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 occlusion_s2 0.7508825566113533 0.5507223865869172
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 occlusion_s3 0.69673471509308 0.49486029669876785
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 occlusion_s4 0.6382778321974915 0.38051570103680904
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 jpeg_s1 0.8169669616194488 0.7516946411802218
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 jpeg_s2 0.8131377000585084 0.7467480938638545
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 jpeg_s3 0.8006984594268464 0.7240170119690953
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 1 jpeg_s4 0.7402308170483378 0.5899384450205821

=== FINAL TEST / RESUME: N0 seed 2 ===
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 clean 0.8163756348100878 0.7559869501352581
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 blur_s1 0.8024402632146357 0.714616026924622
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 blur_s2 0.7494001172345985 0.5380186943236506
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 blur_s3 0.6740366033396326 0.33397989372849346
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 blur_s4 0.5851575716348224 0.18268129930734223
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 brightness_s1 0.8155872731974395 0.7535313250439808
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 brightness_s2 0.8114775763691338 0.7454817924694653
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 brightness_s3 0.7997675053560175 0.7176900244486134
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 brightness_s4 0.7594360964347118 0.5935350637311624
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 rotation_s1 0.8093479020589361 0.7414096239675745
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 rotation_s2 0.7994271998752674 0.7225510599509745
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 rotation_s3 0.7888520082750509 0.7003744986096289
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 rotation_s4 0.7735815630655303 0.6706924864469658
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 occlusion_s1 0.7964223233237894 0.702391775324701
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 occlusion_s2 0.7470063522286846 0.5702205636855742
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 occlusion_s3 0.6881816615217278 0.47906023639929685
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 occlusion_s4 0.6358580475540222 0.3872792800037585
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 jpeg_s1 0.8138901492212861 0.7522671148395433
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 jpeg_s2 0.8099199743662345 0.7462633655962568
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 jpeg_s3 0.7968901739769252 0.7228401089968285
  inference batches: 0 / 156
  inference batches: 80 / 156
N0 2 jpeg_s4 0.7356393510221627 0.5944161063004892

=== FINAL TEST / RESUME: MTL seed 0 ===
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 clean 0.8200680295346902 0.7576762880604507
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 blur_s1 0.8050693410445716 0.7177425296640102
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 blur_s2 0.7532719442098817 0.5620120262989238
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 blur_s3 0.6725512704965843 0.35661837847849726
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 blur_s4 0.5630581983995485 0.1721684641182105
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 brightness_s1 0.8184057759210767 0.7553524377528736
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 brightness_s2 0.8132218568360758 0.7484650549184111
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 brightness_s3 0.8006182452882076 0.7282989703722862
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 brightness_s4 0.7601838455565253 0.6210678674858664
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 rotation_s1 0.8121654722948591 0.7456157928763171
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 rotation_s2 0.8015925973595278 0.725984594091542
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 rotation_s3 0.7888736887181697 0.6967856964725433
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 rotation_s4 0.7703444653393879 0.6549326190446655
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 occlusion_s1 0.8036129255902477 0.7096462671328162
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 occlusion_s2 0.7523682027735473 0.5565585037425209
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 occlusion_s3 0.683742108912433 0.48165073980313505
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 occlusion_s4 0.6255257803512496 0.3991152870470369
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 jpeg_s1 0.8169569019720347 0.7544793844848536
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 jpeg_s2 0.8130454891141955 0.7480848005905562
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 jpeg_s3 0.8000736972466114 0.7262323115048793
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 0 jpeg_s4 0.744469831076378 0.6136414327469714

=== FINAL TEST / RESUME: MTL seed 1 ===
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 clean 0.8195664575253702 0.7580363311386659
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 blur_s1 0.8027571820768475 0.7186020012165703
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 blur_s2 0.7485945104384575 0.559452156677067
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 blur_s3 0.6660513056862754 0.3378213945804816
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 blur_s4 0.5578942882306757 0.1786112800716131
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 brightness_s1 0.8185838136816151 0.7542833669037287
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 brightness_s2 0.8137578904125545 0.7442971725553803
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 brightness_s3 0.8010078701900825 0.715437932787431
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 brightness_s4 0.7609773488408225 0.5865355527739143
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 rotation_s1 0.8098737542021248 0.7403760357694983
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 rotation_s2 0.7982131689851032 0.7156627490039318
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 rotation_s3 0.7861507081305651 0.6867751289122611
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 rotation_s4 0.7707097130700035 0.6504333907544453
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 occlusion_s1 0.8011103209789646 0.7070340501853297
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 occlusion_s2 0.7424529383873534 0.5639506788018341
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 occlusion_s3 0.677144273463456 0.48768667133401417
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 occlusion_s4 0.6250949284251736 0.40191855576321034
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 jpeg_s1 0.8169269675427345 0.75533760517219
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 jpeg_s2 0.813029544040166 0.7501646041772762
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 jpeg_s3 0.7998749196384489 0.7277209229816353
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 1 jpeg_s4 0.7389906002213499 0.6215798790306045

=== FINAL TEST / RESUME: MTL seed 2 ===
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 2 clean 0.8183649669881866 0.7563033520777543
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 2 blur_s1 0.803252255916366 0.7084911365270355
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 2 blur_s2 0.7411259119104443 0.5351104877945744
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 2 blur_s3 0.6352866445654173 0.2837404818323291
  inference batches: 0 / 156
  inference batches: 80 / 156
MTL 2 blur_s4 0.4956600470121897 0.14490267669993673
  inference batches: 0 / 156
  inference batches: 80 / 156

In [9]:
# 9 — Complete reports, paired effects, sample SD and immutable baseline check.
for seed in (0,1,2):
    folder=BASELINE/f'A_seed{seed}'
    assert {name:digest(folder/name) for name in old_runs[str(seed)]}==old_runs[str(seed)],'Historical A changed'
report(PROJECT,CONFIG)
print('Corruption averages (clean excluded):')
display(pd.read_csv(STUDY/'corruption_summary.csv',header=[0,1],index_col=0))
print('Paired seed contrasts in percentage points:')
display(pd.read_csv(STUDY/'paired_seed_contrasts.csv'))
status={}
for name in CONFIG['models']:
    for seed in CONFIG['seeds']:
        folder=STUDY/f'{name}_seed{seed}'
        status[f'{name}_seed{seed}']=dict(
            training=json.loads((folder/'train_complete.json').read_text()),
            checkpoint_sha256=digest(folder/'best_model.pt'),
            thresholds_sha256=digest(folder/'clean_val_thresholds.json'),
            test_sha256=digest(folder/'test_metrics.json'))
write_json(STUDY/'rq5_complete.json',dict(commit=COMMIT,execution_binding=BINDING,
    lambda_value=CONFIG['mtl_lambda'],runs=status,
    note='Three seeds; sample SD is descriptive. Negative findings must be retained.'))
print('RQ5 COMPLETE:',STUDY,flush=True)
print('CSV outputs remain in the new RQ5 folder; old RQ4/Oracle artifacts were not modified.')

Corruption averages (clean excluded):

            mAP           frozen_F1            F1_at_05
           mean       std      mean       std      mean       std
model
A      0.760485  0.002264  0.613690  0.000473  0.564882  0.007329
MTL    0.755648  0.005447  0.618356  0.006477  0.570936  0.012575
N0     0.760157  0.001216  0.613751  0.004459  0.563436  0.007827
N1     0.760220  0.002524  0.610896  0.000920  0.562335  0.009570

Paired seed contrasts in percentage points:

,comparison,scope,seed,delta_mAP_pp,delta_frozen_F1_pp,delta_F1_at_05_pp
0,N1-N0,clean,0,0.042985,0.152076,0.320631
1,N1-N0,clean,1,-0.036899,-0.252878,-0.147007
2,N1-N0,clean,2,0.021616,-0.241581,0.076732
3,MTL-A,clean,0,0.014879,0.104065,-1.461406
4,MTL-A,clean,1,-0.070391,0.379333,0.237446
5,MTL-A,clean,2,-0.041883,0.002231,1.456162
6,N0-A,clean,0,-0.009928,-0.000925,-0.320839
7,N0-A,clean,1,-0.061052,0.114764,-0.663546
8,N0-A,clean,2,-0.240816,-0.029410,-0.047624
9,N1-N0,corrupted,0,0.030122,-0.335327,0.109636
10,N1-N0,corrupted,1,0.219095,0.179518,-0.336220
11,N1-N0,corrupted,2,-0.230359,-0.700845,-0.103689
12,MTL-A,corrupted,0,-0.298737,0.951212,-0.793711
13,MTL-A,corrupted,1,-0.256210,0.689716,0.817319
14,MTL-A,corrupted,2,-0.896226,-0.241123,1.792597
15,N0-A,corrupted,0,-0.139605,-0.102380,-0.475828
16,N0-A,corrupted,1,-0.071664,-0.368523,-0.190896
17,N0-A,corrupted,2,0.112819,0.489207,0.232954

RQ5 COMPLETE: /content/drive/MyDrive/FacialVisualProfile/runs/rq5_training_v1
CSV outputs remain in the new RQ5 folder; old RQ4/Oracle artifacts were not modified.